---
- name: installing docker and python3
  hosts: ec2
  become: yes
  vars: 
    - ansible_python_interpreter: /usr/bin/python
  tasks:
  - name: installing docker and python3
    yum:
      name:
       - docker
       - python3
      state: present
      update_cache: yes

- name: installing docker-compose
  hosts: ec2
  become: yes
  tasks:
    - name: downloading docker compose and install
      get_url:
          url: https://github.com/docker/compose/releases/download/1.29.0/docker-compose-Linux-{{lookup('pipe','uname -m')}}
          dest: /usr/local/bin/docker-compose
          mode: +x